org: wellingtonosilva
app: seu-manuel
frameworkVersion: '~4.17.2'
service: seu-manuel-web

# Set your team ID if you are using Bref Cloud
#bref:
#    team: my-team-id

provider:
    name: aws
    # The AWS region in which to deploy (us-east-1 is the default)
    region: us-east-1
    # Environment variables
    environment:
        APP_ENV: ${sls:stage} # Or use ${sls:stage} if you want the environment to match the stage
        APP_NAME: ${env:APP_NAME}
        APP_KEY: ${env:APP_KEY}
        APP_DEBUG: ${env:APP_DEBUG}
        APP_URL: ${env:APP_URL}
        APP_PORT: ${env:APP_PORT}
        DB_CONNECTION: ${env:DB_CONNECTION}
        DB_HOST: ${env:DB_HOST}
        DB_PORT: ${env:DB_PORT}
        DB_DATABASE: ${env:DB_DATABASE}
        DB_USERNAME: ${env:DB_USERNAME}
        DB_PASSWORD: ${env:DB_PASSWORD}
        SESSION_DRIVER: ${env:SESSION_DRIVER}
        QUEUE_CONNECTION: ${env:QUEUE_CONNECTION}
        CACHE_STORE: ${env:CACHE_STORE}
        OPENAI_API_KEY: ${env:OPENAI_API_KEY}
package:
    # Files and directories to exclude from deployment
    patterns:
        - '!node_modules/**'
        - '!public/storage'
        - '!resources/assets/**'
        - '!resources/css/**'
        - '!resources/images/**'
        - '!resources/js/**'
        - '!storage/**'
        - '!tests/**'
        - '!database/*.sqlite'
        # Exclude assets except for the manifest file
        - '!public/build/**'
        - 'public/build/manifest.json'

functions:

    # This function runs the Laravel website/API
    web:
        handler: public/index.php
        runtime: php-82-fpm
        timeout: 27 # in seconds (API Gateway has a timeout of 29 seconds)
        events:
            - httpApi: '*'

    # This function lets us run artisan commands in Lambda
    artisan:
        handler: artisan
        runtime: php-82-console
        timeout: 720 # in seconds
        # Uncomment to also run the scheduler every minute
        #events:
        #    - schedule:
        #          rate: rate(1 minute)
        #          input: '"schedule:run"'

plugins:
  - ./vendor/bref/bref
  - serverless-lift

constructs:
    website:
        type: server-side-website
        assets:
            '/build/*': public/build
            '/favicon.ico': public/favicon.ico
            '/robots.txt': public/robots.txt
            # add here any file or directory that needs to be served from S3
